[package]
name = "pot"
version = "0.0.0"
description = "A cross-platform translation software"
authors = ["Pylogmon"]
license = "GPLv3"
repository = "https://github.com/Pylogmon/Pot"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "1.2", features = [] }

[dependencies]
serde = { version = "1.0", features = ["derive"] }
tauri = { version = "1.2", features = ["clipboard-all", "fs-write-file", "global-shortcut-all", "http-all", "notification", "notification-all", "shell-open", "system-tray", "window-all"] }
tauri-plugin-single-instance = { git = "https://github.com/tauri-apps/plugins-workspace", branch = "dev" }
once_cell = "1.17.1"
reqwest = "0.11.14"
toml = "0.7.3"

[target.'cfg(windows)'.dependencies]
window-shadows = "0.2"
windows = {version="0.44.0",features= ["Win32_UI_WindowsAndMessaging", "Win32_Foundation"] }
enigo = {git = "https://github.com/enigo-rs/enigo"}
cli-clipboard = "0.4.0"

[target.'cfg(target_os = "macos")'.dependencies ]
window-shadows = "0.2"

[features]
# by default Tauri runs in production mode
# when `tauri dev` runs it is executed with `cargo run --no-default-features` if `devPath` is an URL
default = ["custom-protocol"]
# this feature is used used for production builds where `devPath` points to the filesystem
# DO NOT remove this
custom-protocol = ["tauri/custom-protocol"]
