name: 🐞 Bug
description: 反馈使用过程中遇到的问题
title: "[BUG]: <标题>"
labels: ["bug", "待验证"]
body:
- type: markdown
  attributes:
    value: |
      ## 感谢反馈，pot因您的反馈变得更好！
- type: checkboxes
  attributes:
    label: 提交新Issue前请确认一下事项
    description: |
      1. 我已认真查阅官网使用文档。
      2. 我已查找历史issue但没有找到答案。
    options:
      - label: 我已确认以上事项
        required: true
- type: textarea
  attributes:
    label: 问题描述
    description: 简单描述遇到的问题
  validations:
    required: true
- type: textarea
  attributes:
    label: 如何复现
    description: 详细描述复现问题的步骤
  validations:
    required: true
- type: dropdown
  attributes:
    label: 操作系统
    description: 你使用的操作系统
    options:
      - Windows (Default)
      - Linux
      - MacOS
  validations:
    required: true
- type: textarea
  attributes:
    label: 操作系统版本
    description: 所使用操作系统版本，如：Windows11
  validations:
    required: true
- type: dropdown
  attributes:
    label: 窗口系统(Linux Only)
    options:
      - X11
      - Wayland
- type: textarea
  attributes:
    label: 软件版本
    description: pot软件的版本，可以在设置页面最下方查看。
- type: textarea
  attributes:
    label: 补充信息
    description: 其他需要补充的信息
