on:
  workflow_dispatch:
    inputs:
      tag-name:
        description: 'The git tag name to bump the formula to'
        required: true

jobs:
  homebrew:
    name: Update Homebrew cask
    runs-on: macos-latest
    steps:
      - name: Update Homebrew cask
        env:
          HOMEBREW_GITHUB_API_TOKEN: ${{ secrets.TOKEN }}
        run: |
          brew tap pot-app/homebrew-tap
          brew bump-cask-pr pot --version ${{ github.event.inputs.tag-name }}