name: Notify
on:
  issues:
    types: opened
  issue_comment:
    types: created
  pull_request_target:
    types: opened
  discussion_comment:
    types: created
jobs:
  notify:
    name: Notify
    runs-on: ubuntu-latest
    steps:
      - uses: colutius/Telegram-Msg@main
        with:
          token: ${{ secrets.TELEGRAM_TOKEN }}
          chatid: ${{ secrets.TELEGRAM_CHATID }}
          button: true
          message: |
            📣 New ${{github.event_name}} in pot-desktop

            💡Title: ${{ github.event.issue.title }}${{ github.event.pull_request.title }}${{ github.event.comment.title }}

            👤User: ${{ github.event.sender.login }}

            📄Body: ${{ github.event.comment.body }}${{ github.event.issue.body }}${{ github.event.pull_request.body }}
          button_name: 👀前往查看👀
          button_url: https://github.com/${{ github.repository }}
