name: Notify
on:
  issues:
    types: opened
  issue_comment:
    types: created
  pull_request_target:
    types: opened
  discussion_comment:
    types: created
jobs:
  notify:
    name: Notify
    runs-on: ubuntu-latest
    steps:
      - name: get issue_comment content
        if: github.event_name == 'issue_comment'
        run: |
          echo "CONTENT=\"${{ github.event.comment.body }}\"" >> $GITHUB_ENV
      - name: get discussion_comment content
        if: github.event_name == 'discussion_comment'
        run: |
          echo "CONTENT=\"${{ github.event.comment.body }}\"" >> $GITHUB_ENV
      - name: get issues content
        if: github.event_name == 'issues'
        run: |
          echo "CONTENT=${{ github.event.issue.title }}" >> $GITHUB_ENV
      - name: get pull_request content
        if: github.event_name == 'pull_request_target'
        run: |
          echo "CONTENT=${{ github.event.pull_request.title }}" >> $GITHUB_ENV
      - uses: colutius/Telegram-Msg@main
        with:
          token: ${{ secrets.TELEGRAM_TOKEN }}
          chatid: ${{ secrets.TELEGRAM_CHATID }}
          message: |
            🌟pot-desktop 仓库有新的 ${{github.event_name}}🌟

            ${{ github.event.issue.title }}${{ github.event.pull_request.title }}${{ github.event.comment.title }}

            ${{ github.event.sender.login }}:

            ${{ env.CONTENT }}
