name: Updater

on: workflow_dispatch

jobs:
  release-update:
    runs-on: ubuntu-latest
    if: startsWith(github.repository, 'Pylogmon')
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install git
        run: |
          sudo apt-get update
          sudo apt-get install -y git

      - name: Get Tag Name
        run: |
          echo "VERSION=$(git describe --tags | sed 's/\([^-]*-g\)/r\1/;s/-/./g' | sed 's/.r.*//g')" >> $GITHUB_ENV
          
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: pnpm install
        run: pnpm install

      - name: Release updater file
        run: pnpm run updater
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}

      - name: Upload Release
        uses: softprops/action-gh-release@v1
        with:
          body_path: CHANGELOG
          tag_name: ${{ env.VERSION }}
          token: ${{ secrets.RELEASE_TOKEN }}
          files: update.json