name: Publish to WinGet
on:
  workflow_dispatch:
  release:
    types: [released]
jobs:
  publish:
    # Action can only be run on windows
    runs-on: windows-latest
    steps:
      - name: Publish to WinGet
        if: startsWith(github.ref, 'refs/tags')
        uses: vedantmgoyal2009/winget-releaser@v2
        with:
          identifier: Pylogmon.pot
          max-versions-to-keep: 5
          installers-regex: '\.msi$'
          token: ${{ secrets.RELEASE_TOKEN }}